/* eslint-disable @next/next/no-img-element */
export default function Credit({ title, subtitle, dates }) {
  return (
    <section
      className="footer-copyright spacer-double-sm bg-white text-center"
      style={{ paddingBottom: 0 }}
    >
      <h6 className="mb-0 text-dark-gray">{title}</h6>
      <h1 className="mb-0 font-secondary text-dark-gray">{subtitle}</h1>
      <h6 className="mb-5 text-dark-gray">{dates}</h6>

      <h6 className="mb-0 text-dark-gray">
        hosted on{" "}
        <a
          href="https://firebase.google.com"
          target="_blank"
          rel="noreferrer"
        >
          <img src="/img/firebase.png" alt="firebase" height="26" />
        </a>
        &nbsp;generated by &nbsp;
        <a
          href="https://github.com/lojaya/wedding-page"
          target="_blank"
          rel="noreferrer"
        >
          <img src="/img/github.png" alt="github" height="24" />
        </a>
      </h6>

      <div
        style={{
          maxWidth: "400px",
          width: "auto",
          margin: "0 auto",
          paddingTop: "40px",
        }}
      >
        <img style={{ width: "100%" }} src="/img/flower-footer.png" alt="" />
      </div>
    </section>
  );
}
